# Generated by Django 2.0.1 on 2018-02-22 20:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='es_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='en_slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sub_title',
            new_name='en_sub_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='en_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='en_title',
        ),
        migrations.AddField(
            model_name='post',
            name='es_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='es_sub_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='es_text',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='es_title',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
