# Generated by Django 2.0.1 on 2018-02-01 16:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('crated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carouseles',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frontend/')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('call_to_action_url', models.CharField(blank=True, max_length=144)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('Carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='frontend.Carousel')),
            ],
            options={
                'verbose_name': 'Imágen del carousel',
                'verbose_name_plural': 'Imagenes del carousel',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('es_title', models.CharField(blank=True, max_length=144)),
                ('en_title', models.CharField(blank=True, max_length=144)),
                ('es_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('en_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('es_mision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('en_mision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('es_vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('en_vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('default_lang', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'en'), (2, 'es')], null=True)),
                ('logo', models.ImageField(blank=True, height_field='height_field_logo', null=True, upload_to='site', width_field='width_field_logo')),
                ('logo_sm', models.ImageField(blank=True, height_field='height_field_logo_sm', null=True, upload_to='site', width_field='width_field_logo_sm')),
                ('logo_lg', models.ImageField(blank=True, height_field='height_field_logo_lg', null=True, upload_to='site', width_field='width_field_logo_lg')),
                ('mision_img', models.ImageField(blank=True, height_field='height_field_mision_img', null=True, upload_to='site', width_field='width_field_mision_img')),
                ('vision_img', models.ImageField(blank=True, height_field='height_field_vision_img', null=True, upload_to='site', width_field='width_field_vision_img')),
                ('timeline_img', models.ImageField(blank=True, height_field='height_field_timeline_img', null=True, upload_to='site', width_field='width_field_timeline_img')),
                ('width_field_logo', models.IntegerField(blank=True, default=0)),
                ('height_field_logo', models.IntegerField(blank=True, default=0)),
                ('width_field_logo_sm', models.IntegerField(blank=True, default=0)),
                ('height_field_logo_sm', models.IntegerField(blank=True, default=0)),
                ('width_field_logo_lg', models.IntegerField(blank=True, default=0)),
                ('height_field_logo_lg', models.IntegerField(blank=True, default=0)),
                ('width_field_mision_img', models.IntegerField(blank=True, default=0)),
                ('height_field_mision_img', models.IntegerField(blank=True, default=0)),
                ('width_field_vision_img', models.IntegerField(blank=True, default=0)),
                ('height_field_vision_img', models.IntegerField(blank=True, default=0)),
                ('width_field_timeline_img', models.IntegerField(blank=True, default=0)),
                ('height_field_timeline_img', models.IntegerField(blank=True, default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('latitude', models.DecimalField(decimal_places=8, default=8.6571004, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=8, default=-60.1603678, max_digits=19)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Company')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_description', ckeditor.fields.RichTextField(blank=True)),
                ('es_description', ckeditor.fields.RichTextField(blank=True)),
                ('crated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_desc', models.CharField(blank=True, max_length=144)),
                ('es_desc', models.CharField(blank=True, max_length=144)),
                ('es_title', models.CharField(blank=True, max_length=144)),
                ('en_title', models.CharField(blank=True, max_length=144)),
                ('es_url', models.CharField(blank=True, max_length=144)),
                ('en_url', models.CharField(blank=True, max_length=144)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_description', ckeditor.fields.RichTextField(blank=True)),
                ('es_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('url', models.CharField(blank=True, max_length=144)),
                ('icon', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'behance'), (2, 'dribbble'), (3, 'facebook'), (4, 'flickr'), (5, 'foursquare'), (6, 'github'), (7, 'github-alt'), (8, 'google'), (9, 'google-plus'), (10, 'instagram'), (11, 'joomla'), (12, 'linkedin'), (13, 'pagekit'), (14, 'pinterest'), (15, 'soundcloud'), (16, 'tripadvisor'), (17, 'tumblr'), (18, 'twitter'), (19, 'uikit'), (20, 'vimeo'), (21, 'whatsapp'), (22, 'wordpress'), (23, 'xing'), (24, 'yelp'), (25, 'youtube')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Company')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_description', ckeditor.fields.RichTextField(blank=True)),
                ('es_description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, default='/static/base/images/timeline_default.png', upload_to='timeline')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1948), django.core.validators.MaxValueValidator(2018)])),
                ('place', models.CharField(blank=True, max_length=144)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=144)),
                ('es_name', models.CharField(blank=True, max_length=144)),
                ('en_description', ckeditor.fields.RichTextField(blank=True)),
                ('es_description', ckeditor.fields.RichTextField(blank=True)),
                ('icon', models.CharField(blank=True, choices=[('home', 'home'), ('sign-in', 'sign-in'), ('sign-out', 'sign-out'), ('user', 'user'), ('users', 'users'), ('lock', 'lock'), ('unlock', 'unlock'), ('settings', 'settings'), ('cog', 'cog'), ('nut', 'nut'), ('comment', 'comment'), ('commenting', 'commenting'), ('comments', 'comments'), ('hashtag', 'hashtag'), ('tag', 'tag'), ('cart', 'cart'), ('credit-card', 'credit-card'), ('mail', 'mail'), ('search', 'search'), ('location', 'location'), ('bookmark', 'bookmark'), ('code', 'code'), ('paint-bucket', 'paint-bucket'), ('camera', 'camera'), ('bell', 'bell'), ('bolt', 'bolt'), ('star', 'star'), ('heart', 'heart'), ('happy', 'happy'), ('lifesaver', 'lifesaver'), ('rss', 'rss'), ('social', 'social'), ('git-branch', 'git-branch'), ('git-fork', 'git-fork'), ('world', 'world'), ('calendar', 'calendar'), ('clock', 'clock'), ('history', 'history'), ('future', 'future'), ('pencil', 'pencil'), ('trash', 'trash'), ('move', 'move'), ('link', 'link'), ('question', 'question'), ('info', 'info'), ('warning', 'warning'), ('image', 'image'), ('thumbnails', 'thumbnails'), ('table', 'table'), ('list', 'list'), ('menu', 'menu'), ('grid', 'grid'), ('more', 'more'), ('more-vertical', 'more-vertical'), ('plus', 'plus'), ('plus-circle', 'plus-circle'), ('minus', 'minus'), ('minus-circle', 'minus-circle'), ('close', 'close'), ('check', 'check'), ('ban', 'ban'), ('refresh', 'refresh'), ('play', 'play'), ('play-circle', 'play-circle'), ('Devices', 'Devices'), ('tv', 'tv'), ('desktop', 'desktop'), ('laptop', 'laptop'), ('tablet', 'tablet'), ('phone', 'phone'), ('tablet-landscape', 'tablet-landscape'), ('phone-landscape', 'phone-landscape'), ('Storage', 'Storage'), ('file', 'file'), ('copy', 'copy'), ('file-edit', 'file-edit'), ('folder', 'folder'), ('album', 'album'), ('push', 'push'), ('pull', 'pull'), ('server', 'server'), ('database', 'database'), ('cloud-upload', 'cloud-upload'), ('cloud-download', 'cloud-download'), ('download', 'download'), ('upload', 'upload'), ('Direction', 'Direction'), ('reply', 'reply'), ('forward', 'forward'), ('expand', 'expand'), ('shrink', 'shrink'), ('arrow-up', 'arrow-up'), ('arrow-down', 'arrow-down'), ('arrow-left', 'arrow-left'), ('arrow-right', 'arrow-right'), ('chevron-up', 'chevron-up'), ('chevron-down', 'chevron-down'), ('chevron-left', 'chevron-left'), ('chevron-right', 'chevron-right'), ('triangle-up', 'triangle-up'), ('triangle-down', 'triangle-down'), ('triangle-left', 'triangle-left'), ('triangle-right', 'triangle-right'), ('Editor', 'Editor'), ('bold', 'bold'), ('italic', 'italic'), ('strikethrough', 'strikethrough'), ('video-camera', 'video-camera')], max_length=144, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Company')),
            ],
            options={
                'verbose_name': 'Site values',
                'verbose_name_plural': 'Site values',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='Pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='frontend.Pages'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='frontend.Position'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Page', to='frontend.Position'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='page',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.Pages'),
        ),
    ]
