# Generated by Django 2.0.1 on 2018-02-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carrusel', 'verbose_name_plural': 'Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menú', 'verbose_name_plural': 'Menú'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Posición', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'Imágen del carrusel', 'verbose_name_plural': 'Imagenes del carrusel'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'verbose_name': 'Valores de la empresa', 'verbose_name_plural': 'Valores de la empresa'},
        ),
    ]
