# Generated by Django 2.0.1 on 2018-03-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180319_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'Linea de tiempo grupo PHX', 'verbose_name_plural': 'Linea de tiempo grupo PHX'},
        ),
    ]
