# Generated by Django 2.0.1 on 2018-02-01 18:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import src.brands.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=140)),
                ('es_name', models.CharField(max_length=140)),
                ('en_title', models.CharField(max_length=140)),
                ('es_title', models.CharField(max_length=140)),
                ('en_slug', models.CharField(blank=True, max_length=140)),
                ('es_slug', models.CharField(blank=True, max_length=140)),
                ('short_logo', models.ImageField(upload_to=src.brands.models.Brand._get_upload_to)),
                ('large_logo', models.ImageField(upload_to=src.brands.models.Brand._get_upload_to)),
                ('en_description', ckeditor.fields.RichTextField()),
                ('es_description', ckeditor.fields.RichTextField()),
                ('en_short_description', ckeditor.fields.RichTextField()),
                ('es_short_description', ckeditor.fields.RichTextField()),
                ('url', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frontend/')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('call_to_action_url', models.CharField(blank=True, max_length=144)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brands.Brand')),
            ],
            options={
                'verbose_name': 'Imágen del carousel',
                'verbose_name_plural': 'Imagenes del carousel',
            },
        ),
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=140)),
                ('es_name', models.CharField(blank=True, max_length=140)),
                ('en_description', ckeditor.fields.RichTextField(blank=True)),
                ('es_description', ckeditor.fields.RichTextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='brands/type/')),
                ('short_image', models.ImageField(blank=True, upload_to='brands/type/short/')),
                ('large_image', models.ImageField(blank=True, upload_to='brands/type/large/')),
            ],
            options={
                'verbose_name': 'Business Segment',
                'verbose_name_plural': 'Business Segment',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=140)),
                ('es_name', models.CharField(blank=True, max_length=140)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='brands/cat/')),
                ('short_image', models.ImageField(upload_to='brands/cat/short/')),
                ('large_image', models.ImageField(upload_to='brands/cat/large/')),
            ],
            options={
                'verbose_name': 'Brand Category',
                'verbose_name_plural': 'Brand Category',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=140)),
                ('es_name', models.CharField(blank=True, max_length=140)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='brands/cat/')),
                ('short_image', models.ImageField(upload_to='brands/cat/short/')),
                ('large_image', models.ImageField(upload_to='brands/cat/large/')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=140)),
                ('es_name', models.CharField(max_length=140)),
                ('es_description', models.TextField(blank=True)),
                ('en_description', models.TextField(blank=True)),
                ('es_short_description', models.CharField(blank=True, max_length=500)),
                ('en_short_description', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=140)),
                ('office_number', models.CharField(blank=True, max_length=140)),
                ('phone_number', models.CharField(blank=True, max_length=140)),
                ('google_iframe', models.CharField(blank=True, max_length=220)),
                ('google_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.ManyToManyField(blank=True, to='brands.BusinessModel'),
        ),
    ]
