# Generated by Django 2.0.1 on 2018-02-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmodel',
            options={'verbose_name': 'Segmento de negocio', 'verbose_name_plural': 'Segmentos de negocio'},
        ),
        migrations.AddField(
            model_name='brand',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
