# Generated by Django 2.0.1 on 2018-02-22 16:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import src.brands.models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20180222_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.ManyToManyField(blank=True, to='brands.BusinessModel', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción ingles'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_name',
            field=models.CharField(max_length=140, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, verbose_name='Descripción corta inglés'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_slug',
            field=models.CharField(blank=True, max_length=140, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_title',
            field=models.CharField(max_length=140, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción español'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_name',
            field=models.CharField(max_length=140, verbose_name='Nombre inglés'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, verbose_name='Descripción corta español'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_slug',
            field=models.CharField(blank=True, max_length=140, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_title',
            field=models.CharField(max_length=140, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Marca destacada'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='large_logo',
            field=models.ImageField(upload_to=src.brands.models.Brand._get_upload_to, verbose_name='Logo grande'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_logo',
            field=models.ImageField(upload_to=src.brands.models.Brand._get_upload_to, verbose_name='Logo pequeño'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.CharField(blank=True, max_length=140, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brands.Brand', verbose_name='Marca asociada'),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='call_to_action_url',
            field=models.CharField(blank=True, max_length=144, verbose_name='Boton de enlace'),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='image',
            field=models.ImageField(upload_to='frontend/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='en_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='en_name',
            field=models.CharField(max_length=140, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='es_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='es_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre inglés'),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='brands/type/large/', verbose_name='Imágen grande'),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='short_image',
            field=models.ImageField(blank=True, upload_to='brands/type/short/', verbose_name='Imágen pequeña'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_name',
            field=models.CharField(max_length=140, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='category',
            name='es_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre inglés'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='brands/cat/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='brands/cat/large/', verbose_name='Imágen grande'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_image',
            field=models.ImageField(blank=True, upload_to='brands/cat/short/', verbose_name='Imágen pequeña'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='en_name',
            field=models.CharField(max_length=140, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='department',
            name='es_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre inglés'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(upload_to='brands/cat/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='brands/dep/large/', verbose_name='Imágen grande'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Department', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_image',
            field=models.ImageField(blank=True, upload_to='brands/dep/short/', verbose_name='Imágen pequeña'),
        ),
        migrations.AlterField(
            model_name='department',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='Brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Marca asociada'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.CharField(blank=True, max_length=140, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='location',
            name='en_description',
            field=models.TextField(blank=True, verbose_name='Descripción ingles'),
        ),
        migrations.AlterField(
            model_name='location',
            name='en_name',
            field=models.CharField(max_length=140, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='location',
            name='en_short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripción corta inglés'),
        ),
        migrations.AlterField(
            model_name='location',
            name='es_description',
            field=models.TextField(blank=True, verbose_name='Descripción español'),
        ),
        migrations.AlterField(
            model_name='location',
            name='es_name',
            field=models.CharField(max_length=140, verbose_name='Nombre inglés'),
        ),
        migrations.AlterField(
            model_name='location',
            name='es_short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripción corta español'),
        ),
        migrations.AlterField(
            model_name='location',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_iframe',
            field=models.CharField(blank=True, max_length=220, verbose_name='Enlace a iframe'),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='location',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='location',
            name='office_number',
            field=models.CharField(blank=True, max_length=140, verbose_name='Número de oficina'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=140, verbose_name='Número de telefono'),
        ),
        migrations.AlterField(
            model_name='location',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Twitter'),
        ),
    ]
