# Generated by Django 2.0.1 on 2018-02-22 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20180222_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_short_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción corta inglés'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_short_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción corta español'),
        ),
    ]
