# Generated by Django 2.0.1 on 2018-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20180222_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.ManyToManyField(blank=True, to='brands.BusinessModel'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_slug',
            field=models.CharField(blank=True, max_length=140, verbose_name='URL Slug español'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='es_slug',
            field=models.CharField(blank=True, max_length=140, verbose_name='URL Slug inglés'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.CharField(blank=True, max_length=140, verbose_name='Dirección url de la marca'),
        ),
    ]
