# Generated by Django 2.0.1 on 2018-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20180222_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='en_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre español'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, upload_to='brands/cat/', verbose_name='Imágem principal'),
        ),
    ]
