# Generated by Django 2.0.1 on 2018-02-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_auto_20180222_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='brands.Category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.Department'),
            preserve_default=False,
        ),
    ]
