# Generated by Django 2.0.1 on 2018-02-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_auto_20180222_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.ManyToManyField(blank=True, to='brands.BusinessModel', verbose_name='Modelo de negocio'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='brands.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Department', verbose_name='Departamento'),
        ),
    ]
