# Generated by Django 2.0.1 on 2018-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0015_auto_20180228_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='en_slug',
            field=models.CharField(blank=True, max_length=140, verbose_name='URL Slug español'),
        ),
        migrations.AddField(
            model_name='department',
            name='es_slug',
            field=models.CharField(blank=True, max_length=140, verbose_name='URL Slug inglés'),
        ),
    ]
