# Generated by Django 2.0.1 on 2018-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_auto_20180228_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='department',
        ),
        migrations.AddField(
            model_name='brand',
            name='department',
            field=models.ManyToManyField(blank=True, to='brands.Department', verbose_name='Departamentos'),
        ),
    ]
