# Generated by Django 2.0.1 on 2018-03-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0017_auto_20180228_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['es_name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
